require 'twitter_friends/struct_model/model_common'
require 'twitter_friends/struct_model/twitter_user'
require 'twitter_friends/struct_model/tweet'
require 'twitter_friends/struct_model/relationship'
require 'twitter_friends/struct_model/text_element'
require 'twitter_friends/struct_model/user_metrics'
require 'twitter_friends/struct_model/user_graph_metrics'
require 'twitter_friends/struct_model/user_scraping_metrics'
