require 'wuclan/models/model_common'
require 'wuclan/models/twitter_user'
require 'wuclan/models/tweet'
require 'wuclan/models/relationship'
require 'wuclan/models/text_element'
require 'wuclan/models/user_metrics'
require 'wuclan/models/user_graph_metrics'
require 'wuclan/models/user_scraping_metrics'
